name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manuális indítás engedélyezése

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: 📦 Install dependencies
      run: |
        npm init -y
        npm install vite --save-dev
        
    - name: 🔨 Build with environment variables
      env:
        VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        VITE_XAI_PROVIDER: ${{ secrets.XAI_PROVIDER }}
        VITE_XAI_DEBUG: ${{ secrets.XAI_DEBUG }}
      run: |
        # Simple build mivel nincs build tool beállítva
        mkdir -p dist
        cp -r * dist/ || true
        # Environment variables injektálása
        echo "window.ENV = { VITE_OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}', VITE_XAI_PROVIDER: '${{ secrets.XAI_PROVIDER }}', VITE_XAI_DEBUG: '${{ secrets.XAI_DEBUG }}' };" > dist/env-config.js
        
    - name: 📄 Setup Pages
      uses: actions/configure-pages@v4
      
    - name: 📤 Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 🚀 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
